                     List of relations
 Schema |               Name                | Type  | Owner 
--------+-----------------------------------+-------+-------
 public | access_logs                       | table | kyle
 public | account_transactions              | table | kyle
 public | accounts                          | table | kyle
 public | active_storage_attachments        | table | kyle
 public | active_storage_blobs              | table | kyle
 public | active_storage_variant_records    | table | kyle
 public | agencies                          | table | kyle
 public | agency_settings                   | table | kyle
 public | alerts                            | table | kyle
 public | ar_internal_metadata              | table | kyle
 public | cashier_sessions                  | table | kyle
 public | clients                           | table | kyle
 public | damage_reports                    | table | kyle
 public | drivers                           | table | kyle
 public | drivers_vehicles                  | table | kyle
 public | fare_rules                        | table | kyle
 public | findings                          | table | kyle
 public | inspection_job_parts              | table | kyle
 public | inspection_jobs                   | table | kyle
 public | inspections                       | table | kyle
 public | internal_pos                      | table | kyle
 public | inventory_transactions            | table | kyle
 public | invoices                          | table | kyle
 public | job_dependencies                  | table | kyle
 public | job_template_parts                | table | kyle
 public | job_template_vehicle_applications | table | kyle
 public | job_templates                     | table | kyle
 public | ledger_entries                    | table | kyle
 public | maintenance_parts                 | table | kyle
 public | maintenance_requests              | table | kyle
 public | maintenance_tasks                 | table | kyle
 public | maintenances                      | table | kyle
 public | mechanic_assignments              | table | kyle
 public | monthly_statements                | table | kyle
 public | notifications                     | table | kyle
 public | parts                             | table | kyle
 public | parts_request_items               | table | kyle
 public | parts_requests                    | table | kyle
 public | parts_stores                      | table | kyle
 public | payables                          | table | kyle
 public | payment_audits                    | table | kyle
 public | payment_histories                 | table | kyle
 public | payment_schedules                 | table | kyle
 public | payments                          | table | kyle
 public | permissions                       | table | kyle
 public | pos_transactions                  | table | kyle
 public | purchase_order_items              | table | kyle
 public | purchase_orders                   | table | kyle
 public | purchase_request_items            | table | kyle
 public | purchase_requests                 | table | kyle
 public | purchases                         | table | kyle
 public | quickbooks_integrations           | table | kyle
 public | quickbooks_settings               | table | kyle
 public | quotation_job_parts               | table | kyle
 public | quotation_jobs                    | table | kyle
 public | quotation_line_items              | table | kyle
 public | quotations                        | table | kyle
 public | reception_logs                    | table | kyle
 public | rfq_line_items                    | table | kyle
 public | rfqs                              | table | kyle
 public | role_permissions                  | table | kyle
 public | roles                             | table | kyle
 public | routes                            | table | kyle
 public | schema_migrations                 | table | kyle
 public | service_providers                 | table | kyle
 public | stores                            | table | kyle
 public | suppliers                         | table | kyle
 public | transactions                      | table | kyle
 public | trips                             | table | kyle
 public | user_roles                        | table | kyle
 public | users                             | table | kyle
 public | vehicle_catalog_entries           | table | kyle
 public | vehicle_condition_reports         | table | kyle
 public | vehicle_documents                 | table | kyle
 public | vehicle_statuses                  | table | kyle
 public | vehicles                          | table | kyle
 public | vendor_invoice_items              | table | kyle
 public | vendor_invoices                   | table | kyle
 public | vendor_parts                      | table | kyle
 public | vendor_quotation_lines            | table | kyle
 public | vendor_quotations                 | table | kyle
 public | vendor_rfq_items                  | table | kyle
 public | vendor_rfq_responses              | table | kyle
 public | vendor_rfqs                       | table | kyle
 public | z_reports                         | table | kyle
(85 rows)

