# config/database.yml
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: fleet_management_dev
  username: kyle
  password: kyle9876
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: fleet_management_test
  username: kyle
  password: kyle9876
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  database: db/production.sqlite3